server:
  port: 8090
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/publiclibrary
    username: user
    password: secret
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  liquibase:
    change-log: db/changelog.xml
  jpa:
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html; charset=utf-8
