currency: USD
book.page.size: 5

server:
  servlet:
    context-path: /library
  port: 8090
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
    include-message: never

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/publiclibrary
    username: user
    password: secret
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  liquibase:
    change-log: db/changelog.xml
  jpa:
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html; charset=utf-8
  messages:
    encoding: UTF-8
    basename: language/messages

  mail:
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      springframework:
        security: TRACE
        web:
          FilterChainProxy: TRACE
